- eventhandler_test.go
- eventhandlers.go
- test-events/action-triggered.json
- test-events/configuration-change.http
- test-events/configuration-change.json
- test-events/configure-monitoring.json
- test-events/deployment-finished.json
- test-events/evaluation-done.json
- test-events/get-sli.http
- test-events/get-sli.json
- test-events/problem.json
- test-events/start-evaluation.json
- test-events/tests-finished.http
- test-events/tests-finished.json
I am currently working on a sample SLI provider I will be using for Neotys PAC Event. In that work I found that it would be helpful for anybody writing their own SLI provider to have a pre-defined handler function for InternalGetSLIEvent - similar to all the other helper functions already in that template.
This PR adds this functions including some tips & tricks when filling in the actual code
> adding handler for internalgetslievent

- README.md
- deploy/service.yaml
Closes #9.
This PR adds information about RBAC / roles for the deployment files.
> #9 added information about service account/rbac

- .github/workflows/reviewdog.yml
Signed-off-by: warber <bernd.warmuth@dynatrace.com>
> updated reviewdog

- .github/dependabot.yml
- .github/workflows/CI.yml
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
* Use docker login action (instead of the bash script)
* Added dependabot for automated dependency updates
> Added dependabot, updated CI workflow with docker login action

- go.mod
- go.sum
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
updated go-utils to 0.8.0
> Update go-utils to 0.8.0

- helm/.helmignore
- helm/Chart.yaml
- helm/README.md
- helm/templates/_helpers.tpl
- helm/templates/deployment.yaml
- helm/templates/service.yaml
- helm/templates/serviceaccount.yaml
- helm/templates/tests/test-api-connection.yaml
- helm/values.schema.json
- helm/values.yaml
For #36 
Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>
> adding helm chart for exec plane

- .github/workflows/CI.yml
- .github/workflows/reviewdog.yml
- Dockerfile
- deploy/service.yaml
- go.mod
Upgrade all relevant parts to Go 1.16
Also ugprade distributor to use Keptn 0.8.2
> Upgrade to Go 1.16

- eventhandlers.go
- go.mod
- go.sum
- main.go
> Keptn 0.8.3 compat: remove remediation cloudevent, add get-action

- README.md
- deploy/service.yaml
- go.mod
- go.sum
use keptn/distributor:0.8.3 and go-utils v0.8.4
> Upgrade to Keptn 0.8.3

- .github/workflows/validate-semantic-pr.yml
- adds a semantic PR workflow
FYI @mowies
> Added semantic PR workflow

- .github/actions/unit-tests/action.yml
- .github/workflows/CI.yml
- .versionrc.json
- README.md
- renovate.json
- updates the CI pipeline to make use of re-usable actions
> feat: introduce updated CI pipeline

- deploy/service.yaml
- updates keptn/distributor to version 0.11.3
> feat: Use keptn/distributor 0.11.3

- .ci_env
- .github/workflows/initrepo.yml
- README.md
- chart/README.md
- chart/values.yaml
- skaffold.yaml
Create a new workflow that will update all the necessary files after clicking the `Use this template` button in github.
The workflow has to be triggered manually and it will open a pull request on the new repository.
> build: introduce repository init action

- chart/templates/deployment.yaml
- eventhandlers.go
- main.go
Implement graceful shutdown in `keptn-service-template` as described in #73.
#73
> feat: Implement graceful shutdown

- chart/templates/deployment.yaml
- main.go
Implement liveness and readiness endpoints and use them in Helm files.
#110
> feat: Implement liveness and readiness endpoints

- .github/actions/unit-tests/action.yml
Signed-off-by: Paolo Chila <paolo.chila@dynatrace.com>
> ci: add gotestsum for better unit tests output

- main.go
Signed-off-by: Paolo Chila <paolo.chila@dynatrace.com>
> refactor: restructure graceful shutdown

- README.md
added a warning about being incompatible with Keptn 0.14.x
> docs: added info about incompatibility with Keptn 0.14.x

- .github/workflows/CI.yml
- .github/workflows/integration_tests.yml
- Fixes the Helm chart installation issue (The Helm chart was using an image that was not built)
- Refactors the Github Action code
> fix: Integration test bugs

- .github/workflows/integration_tests.yml
Update Keptn versions in integration tests
* Add 0.15.0
* Remove: 0.11.x
* Change: 0.14.1 -> 0.14.2
* Change: 0.13.4 -> 0.13.5
* Change: 0.12.6 -> 0.12.7
> chore: Update Keptn versions in integration tests

- .github/actions/unit-tests/action.yml
- .github/workflows/CI.yml
- .github/workflows/initrepo.yml
- .github/workflows/integration_tests.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
Signed-off-by: Ladislav Prskavec <ladislav@prskavec.net>
> build(deps): Upgrade setup-go action to use go.mod as a version file

- .github/workflows/initrepo.yml
Update initrepo.yml reference to old event handler file location that is breaking worflow.
Closes issue: https://github.com/keptn-sandbox/keptn-service-template-go/issues/164
Signed-off-by: Brad McCoy <bradmccoydev@gmail.com>
> chore: update event handler location
